In [92]:
import pandas as pd
import os

# ==============================================================================
#1. CLIENTS
# ==============================================================================

#Translation of Clients file
clients = "Clients.xlsx"

if os.path.exists(clients):
    df_clients = pd.read_excel(clients, header=0)
    print(f"The file {clients} is uploaded successfully!")
    display(df_clients.head(10))
else:
    print(f"ERROR: The file is not found {clients}. Make sure to upload the file to google colab.")
    print("Available folders:", [f for f in os.listdir('.') if os.path.isfile(f)])

The file Clients.xlsx is uploaded successfully!

  ID klienta Nazwa    Miasto   Branża
0         K1   ABC   Wrocław       IT
1         K2   BCD   Wrocław   Retail
2         K3   CDE   Wrocław       IT
3         K4   DEF   Wrocław   Retail
4         K5   EFG   Wrocław       IT
5         K6   FGH  Warszawa  Finanse
6         K7   GHI  Warszawa   Retail
7         K8   HIJ  Warszawa   Retail
8         K9   IJK  Warszawa       IT
9        K10   JKL  Warszawa  Finanse

In [93]:
# Clients Dictionary: Polish column name → English column name

df_clients = df_clients.rename(columns ={
    "ID klienta": "client_id",
    "Nazwa": "name",
    "Miasto": "city",
    "Branża": "industry"
})


# Translate text values in the "industry" column
# Map: Polish value → English value
industry_map = {
    "IT":       "IT",        # unchanged
    "Retail":   "Retail",    # unchanged
    "Finanse":  "Finance",
}
df_clients["industry"] = df_clients["industry"].map(industry_map)
df_clients.head()

  client_id name     city industry
0        K1  ABC  Wrocław       IT
1        K2  BCD  Wrocław   Retail
2        K3  CDE  Wrocław       IT
3        K4  DEF  Wrocław   Retail
4        K5  EFG  Wrocław       IT

In [94]:
# Save the translated file
df_clients.to_csv("clients_translated.csv", index=False, encoding="utf-8-sig")

# Download it to your computer
from google.colab import files
files.download("clients_translated.csv")

In [95]:
# ==============================================================================
#2.COSTS
# ==============================================================================

#Upload of Costs file
costs = "Costs.csv"

if os.path.exists(costs):
    df_costs = pd.read_csv(costs, header = 1)
    print(f"The file {costs} is uploaded successfully!")
    display(df_costs.head(10))
else:
    print(f"ERROR: The file is not found {costs}. Make sure to upload the file to google colab.")
    print("Available folders:", [f for f in os.listdir('.') if os.path.isfile(f)])

The file Costs.csv is uploaded successfully!

         Data  Projekt    Koszt
0  28.10.2012       99  PLN 4249
1  29.10.2012       29  PLN 3531
2  30.10.2012       97  PLN 3952
3  31.10.2012       60  PLN 4466
4  01.11.2012       43  PLN 3198
5  02.11.2012       67  PLN 3661
6  03.11.2012       12  PLN 3531
7  04.11.2012       47  PLN 5659
8  05.11.2012       63  PLN 3290
9  06.11.2012       92  PLN 5362

In [96]:
# Costs Dictionary: Polish column name → English column name

#removing space in the headers
df_costs.columns = df_costs.columns.str.strip()

#translation
df_costs = df_costs.rename(columns ={
    "Data": "date",
    "Projekt": "project",
    "Koszt": "cost",
})

#PLN removal from costs values
df_costs['cost'] = df_costs['cost'].str.replace('PLN ', '', regex = False)
df_costs.head()

         date  project  cost
0  28.10.2012       99  4249
1  29.10.2012       29  3531
2  30.10.2012       97  3952
3  31.10.2012       60  4466
4  01.11.2012       43  3198

In [97]:
# Save the translated file
df_costs.to_csv("costs_translated.csv", index=False, encoding="utf-8-sig")

# Download it to laptop
from google.colab import files
files.download("costs_translated.csv")

In [98]:
# ==============================================================================
#3.INVOICES
# ========================================================================

#Upload of Invoices file
invoices = "Invoices.csv"

if os.path.exists(invoices):
    df_invoices = pd.read_csv(invoices, sep=";", header = 0, encoding="windows-1250")
    print(f"The file {invoices} is uploaded successfully!")
    display(df_invoices.head(10))
else:
    print(f"ERROR: The file is not found {invoices}. Make sure to upload the file to google colab.")
    print("Available folders:", [f for f in os.listdir('.') if os.path.isfile(f)])

The file Invoices.csv is uploaded successfully!

   Nr faktury  Projekt  Wartość netto  Data wystawienia
0           1       84    26 800.00 zł        9/29/2012
1           2       52    21 200.00 zł        9/30/2012
2           3       27     6 900.00 zł        10/5/2012
3           4       74    17 900.00 zł        10/8/2012
4           5       30    14 600.00 zł        10/9/2012
5           6       56    27 300.00 zł       10/12/2012
6           7       37     9 800.00 zł       10/14/2012
7           8        4    21 200.00 zł       10/15/2012
8           9        4    15 400.00 zł       10/18/2012
9          10       16    23 700.00 zł       10/22/2012

In [99]:
# Invoices Dictionary: Polish column name → English column name

#removing space in the headers
df_invoices.columns = df_invoices.columns.str.strip()

#translation
df_invoices = df_invoices.rename(columns ={
    "Nr faktury": "invoice_id",
    "Projekt": "project",
    "Wartość netto": "net_value",
    "Data wystawienia": "invoice_date"
})

#zł removal from costs values
df_invoices['net_value'] = df_invoices['net_value'].str.replace(' zł', '', regex = False)

df_invoices.head()

   invoice_id  project  net_value invoice_date
0           1       84  26 800.00    9/29/2012
1           2       52  21 200.00    9/30/2012
2           3       27   6 900.00    10/5/2012
3           4       74  17 900.00    10/8/2012
4           5       30  14 600.00    10/9/2012

In [100]:
# Save the translated file
df_invoices.to_csv("invoices_translated.csv", index=False)

# Download it to laptop
from google.colab import files
files.download("invoices_translated.csv")

In [101]:
# ==============================================================================
#4.PROJECTS
# ========================================================================
#Upload of Projects file
projects = "Projects.csv"

if os.path.exists(projects):
    df_projects = pd.read_csv(projects, sep=";", header = 0, encoding="windows-1250")
    print(f"The file {projects} is uploaded successfully!")
    display(df_projects.head())
else:
    print(f"ERROR: The file is not found {projects}. Make sure to upload the file to google colab.")
    print("Available folders:", [f for f in os.listdir('.') if os.path.isfile(f)])

The file Projects.csv is uploaded successfully!

   Nr projektu  Klient              Rodzaj
0            1      11       Wdrożenie ERP
1            2       1                  BI
2            3       8  Usługi szkoleniowe
3            4      13       Wdrożenie ERP
4            5       4                  BI

In [116]:
# Projects Dictionary: Polish column name → English column name

#removing space in the headers
df_projects.columns = df_projects.columns.str.strip()

#translation
df_projects.columns = ["project_id", "client_id", "project_type"]
df_projects.head()

   project_id  client_id        project_type
0           1         11  erp_implementation
1           2          1                  BI
2           3          8   training_services
3           4         13  erp_implementation
4           5          4                  BI

In [103]:
print(df_projects["project_type"].unique())

df_projects["project_type"] = df_projects["project_type"].str.strip()

project_type_map = {
    "Wdrożenie ERP":        "erp_implementation",
    "BI":                    "BI",    # unchanged
    "Usługi szkoleniowe":  "training_services",
}

df_projects["project_type"] = df_projects["project_type"].map(project_type_map)
df_projects.head()

['Wdrożenie ERP' 'BI' 'Usługi szkoleniowe']

   project_id  client_id        project_type
0           1         11  erp_implementation
1           2          1                  BI
2           3          8   training_services
3           4         13  erp_implementation
4           5          4                  BI

In [105]:
# Save the translated file
df_projects.to_csv("projects_translated.csv", index=False)

# Download it to laptop
from google.colab import files
files.download("projects_translated.csv")

In [108]:
import chardet

with open("External_costs.txt", "rb") as f:
    result = chardet.detect(f.read())

print(result)

{'encoding': 'Windows-1252', 'confidence': 0.73, 'language': ''}

In [112]:
# ==============================================================================
#5.EXTERNAL COSTS
# ========================================================================

#File upload

external_costs = "External_costs.txt"

if os.path.exists(external_costs):
    df_ext = pd.read_csv(external_costs, sep="\t", header=0, encoding="windows-1252", engine="python")
    print(f"The file {external_costs} is uploaded successfully!")
    print(df_ext.columns.tolist())
    display(df_ext.head(10))
else:
    print(f"ERROR: The file is not found {external_costs}. Make sure to upload the file to google colab.")
    print("Available files:", [f for f in os.listdir('.') if os.path.isfile(f)])

The file External_costs.txt is uploaded successfully!
['Data', 'Projekt', ' Warto˜† netto ']

         Data  Projekt  Warto˜† netto
0  29.11.2012       37    5 300.00 zˆ
1  03.12.2012       34    7 500.00 zˆ
2  20.12.2012       35    6 000.00 zˆ
3  08.01.2013       89    9 700.00 zˆ
4  17.01.2013       20    8 300.00 zˆ
5  03.02.2013       49    7 000.00 zˆ
6  11.02.2013        6    4 500.00 zˆ
7  20.02.2013       28    6 100.00 zˆ
8  12.03.2013       32    7 300.00 zˆ
9  25.03.2013       43    7 800.00 zˆ

In [117]:
df_ext.columns = ["date", "project_id", "net_value"]
df_ext["net_value"] = df_ext["net_value"].str.replace(" zˆ", "", regex=False).str.strip()
df_ext.head()

         date  project_id net_value
0  29.11.2012          37  5 300.00
1  03.12.2012          34  7 500.00
2  20.12.2012          35  6 000.00
3  08.01.2013          89  9 700.00
4  17.01.2013          20  8 300.00

In [118]:
df_ext.to_csv("external_costs_translated.csv", index=False, encoding="utf-8-sig")

from google.colab import files
files.download("external_costs_translated.csv")